// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: lvgl-demo

#include "../ui.h"

lv_obj_t * ui_screen_main = NULL;
lv_obj_t * ui_Logo = NULL;
lv_obj_t * ui_guage_speed = NULL;
lv_obj_t * ui_guage_temp_motor = NULL;
lv_obj_t * ui_DNR = NULL;
lv_obj_t * ui_guage_battery_soc = NULL;
lv_obj_t * ui_guage_temp_inverter = NULL;
// event funtions

// build funtions

void ui_screen_main_screen_init(void)
{
    ui_screen_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Logo = lv_img_create(ui_screen_main);
    lv_img_set_src(ui_Logo, &ui_img_emboo_logosunsetorange_png);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Logo, 20);
    lv_obj_set_y(ui_Logo, -128);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Logo, 20);

    ui_guage_speed = lv_arc_create(ui_screen_main);
    lv_obj_set_width(ui_guage_speed, 150);
    lv_obj_set_height(ui_guage_speed, 150);
    lv_obj_set_x(ui_guage_speed, -234);
    lv_obj_set_y(ui_guage_speed, -35);
    lv_obj_set_align(ui_guage_speed, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_guage_speed, 50);

    ui_guage_temp_motor = lv_bar_create(ui_screen_main);
    lv_bar_set_value(ui_guage_temp_motor, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_guage_temp_motor, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_guage_temp_motor, 150);
    lv_obj_set_height(ui_guage_temp_motor, 10);
    lv_obj_set_x(ui_guage_temp_motor, 14);
    lv_obj_set_y(ui_guage_temp_motor, 132);
    lv_obj_set_align(ui_guage_temp_motor, LV_ALIGN_CENTER);

    ui_DNR = lv_label_create(ui_screen_main);
    lv_obj_set_width(ui_DNR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DNR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DNR, 14);
    lv_obj_set_y(ui_DNR, -13);
    lv_obj_set_align(ui_DNR, LV_ALIGN_CENTER);

    ui_guage_battery_soc = lv_arc_create(ui_screen_main);
    lv_obj_set_width(ui_guage_battery_soc, 150);
    lv_obj_set_height(ui_guage_battery_soc, 150);
    lv_obj_set_x(ui_guage_battery_soc, 282);
    lv_obj_set_y(ui_guage_battery_soc, -42);
    lv_obj_set_align(ui_guage_battery_soc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_guage_battery_soc, 50);

    ui_guage_temp_inverter = lv_bar_create(ui_screen_main);
    lv_bar_set_value(ui_guage_temp_inverter, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_guage_temp_inverter, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_guage_temp_inverter, 150);
    lv_obj_set_height(ui_guage_temp_inverter, 10);
    lv_obj_set_x(ui_guage_temp_inverter, 15);
    lv_obj_set_y(ui_guage_temp_inverter, 163);
    lv_obj_set_align(ui_guage_temp_inverter, LV_ALIGN_CENTER);

}

void ui_screen_main_screen_destroy(void)
{
    if(ui_screen_main) lv_obj_del(ui_screen_main);

    // NULL screen variables
    ui_screen_main = NULL;
    ui_Logo = NULL;
    ui_guage_speed = NULL;
    ui_guage_temp_motor = NULL;
    ui_DNR = NULL;
    ui_guage_battery_soc = NULL;
    ui_guage_temp_inverter = NULL;

}
