// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: lvgl-demo

#ifndef UI_SCREEN_CHARGING_H
#define UI_SCREEN_CHARGING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_charging
extern void ui_screen_charging_screen_init(void);
extern void ui_screen_charging_screen_destroy(void);
extern lv_obj_t * ui_screen_charging;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

