// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: lvgl-demo

#ifndef UI_SCREEN_MAIN_H
#define UI_SCREEN_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_main
extern void ui_screen_main_screen_init(void);
extern void ui_screen_main_screen_destroy(void);
extern lv_obj_t * ui_screen_main;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_guage_speed;
extern lv_obj_t * ui_guage_temp_motor;
extern lv_obj_t * ui_DNR;
extern lv_obj_t * ui_guage_battery_soc;
extern lv_obj_t * ui_guage_temp_inverter;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

