// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: lvgl-demo

#include "../ui.h"

lv_obj_t * ui_screen_charging = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions

// build funtions

void ui_screen_charging_screen_init(void)
{
    ui_screen_charging = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_charging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_screen_charging, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_charging, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_screen_charging);
    lv_img_set_src(ui_Image4, &ui_img_emboo_logosunsetorange_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1181
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1181
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, -100);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 40);

}

void ui_screen_charging_screen_destroy(void)
{
    if(ui_screen_charging) lv_obj_del(ui_screen_charging);

    // NULL screen variables
    ui_screen_charging = NULL;
    ui_Image4 = NULL;

}
