// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: lvgl-demo

#ifndef UI_SCREEN_MAIN_H
#define UI_SCREEN_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_main
extern void ui_screen_main_screen_init(void);
extern void ui_screen_main_screen_destroy(void);
extern lv_obj_t * ui_screen_main;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_DNRlabel;
extern lv_obj_t * ui_TRQgauge;
extern lv_obj_t * ui_SPEEDlabel;
extern lv_obj_t * ui_BATPOWERgauge;
extern lv_obj_t * ui_BATSOClabel;
extern lv_obj_t * ui_TEMPbar;
extern lv_obj_t * ui_TEMPvalue;
extern lv_obj_t * ui_TEMPname;
extern lv_obj_t * ui_TEMPbar1;
extern lv_obj_t * ui_TEMPvalue1;
extern lv_obj_t * ui_TEMPname1;
extern lv_obj_t * ui_TEMPbar2;
extern lv_obj_t * ui_TEMPvalue2;
extern lv_obj_t * ui_TEMPname2;
// CUSTOM VARIABLES
extern lv_obj_t * ui_SpeedLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

