#!/bin/bash
# Troubleshoot Victron touchscreen with micro HDMI adapter

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${RED}================================================================${NC}"
echo -e "${RED}   CRITICAL: Micro HDMI Adapter Issue Detected${NC}"
echo -e "${RED}================================================================${NC}"
echo ""

echo -e "${YELLOW}Problem Identified:${NC}"
echo "  You're using a micro HDMI to HDMI adapter."
echo "  Many adapters ONLY pass video, NOT I2C/DDC signals!"
echo ""
echo "  The I2C scan shows ZERO devices (not even EDID at 0x50)."
echo "  This confirms the adapter is blocking I2C communication."
echo ""

echo -e "${BLUE}================================================================${NC}"
echo -e "${BLUE}   Solutions (Try in Order)${NC}"
echo -e "${BLUE}================================================================${NC}"
echo ""

echo -e "${GREEN}SOLUTION 1: Try the Other HDMI Port${NC}"
echo "  The Raspberry Pi 4 has TWO micro HDMI ports (HDMI0 and HDMI1)."
echo "  I2C might only work on one of them."
echo ""
echo "  Current status:"
vcgencmd get_config int | grep hdmi
echo ""
echo "  ${YELLOW}ACTION:${NC}"
echo "    1. Power off the Pi: sudo poweroff"
echo "    2. Move the micro HDMI cable to the OTHER port"
echo "       (If you're using the port closest to USB-C power, try the other one)"
echo "    3. Power on and run: ./check-touchscreen-hardware.sh"
echo ""
read -p "Press Enter to see Solution 2..."
echo ""

echo -e "${GREEN}SOLUTION 2: Get a Proper Micro HDMI Cable${NC}"
echo "  ${RED}RECOMMENDED SOLUTION${NC}"
echo ""
echo "  Replace the micro HDMI → HDMI adapter + HDMI cable with:"
echo "  ${BLUE}✓ A single micro HDMI to HDMI cable${NC}"
echo "    (No adapters - direct cable)"
echo ""
echo "  Why? Adapters often don't pass I2C/DDC pins properly."
echo "  A proper cable has all pins connected end-to-end."
echo ""
echo "  Look for:"
echo "    - \"Micro HDMI to HDMI cable\" (NOT adapter)"
echo "    - \"HDMI 2.0 or 2.1\" specification"
echo "    - Length: 1-2 meters is ideal"
echo ""
echo "  Example searches:"
echo "    - Amazon: 'Micro HDMI to HDMI cable Raspberry Pi 4'"
echo "    - Should cost £5-15 / \$8-20"
echo ""
read -p "Press Enter to see Solution 3..."
echo ""

echo -e "${GREEN}SOLUTION 3: Enable HDMI I2C Support${NC}"
echo "  Force enable I2C on the HDMI port in config.txt"
echo ""
echo "  ${YELLOW}ACTION:${NC}"
echo "    1. Edit boot config:"
echo "       sudo nano /boot/firmware/config.txt"
echo ""
echo "    2. Add these lines at the end:"
echo "       # Force HDMI I2C/DDC"
echo "       hdmi_force_hotplug=1"
echo "       hdmi_ignore_edid=0xa5000080"
echo "       hdmi_force_edid_audio=1"
echo ""
echo "    3. Save and reboot: sudo reboot"
echo ""
echo "    4. After reboot, run: ./check-touchscreen-hardware.sh"
echo ""
read -p "Press Enter to see Solution 4..."
echo ""

echo -e "${GREEN}SOLUTION 4: Test Adapter with Different Device${NC}"
echo "  Verify if the adapter supports I2C/DDC:"
echo ""
echo "  ${YELLOW}ACTION:${NC}"
echo "    1. Connect the adapter to a laptop/desktop"
echo "    2. On Linux/Mac, check EDID:"
echo "       get-edid | parse-edid"
echo "       (or use: ddcutil detect)"
echo ""
echo "    3. If EDID doesn't work on laptop either → adapter is bad"
echo "    4. If EDID works on laptop → Pi configuration issue"
echo ""
read -p "Press Enter to see Solution 5..."
echo ""

echo -e "${GREEN}SOLUTION 5: Check Adapter Specifications${NC}"
echo "  Look at the adapter's product page/documentation:"
echo ""
echo "  ${RED}BAD signs (adapter won't work):${NC}"
echo "    ✗ \"Video only\""
echo "    ✗ \"Does not support DDC\""
echo "    ✗ \"No I2C passthrough\""
echo "    ✗ Costs less than £2 / \$3"
echo ""
echo "  ${GREEN}GOOD signs (adapter might work):${NC}"
echo "    ✓ \"Full HDMI specification\""
echo "    ✓ \"DDC/EDID support\""
echo "    ✓ \"All 19 pins connected\""
echo "    ✓ Gold-plated contacts"
echo ""
echo ""

echo -e "${BLUE}================================================================${NC}"
echo -e "${BLUE}   Quick Decision Tree${NC}"
echo -e "${BLUE}================================================================${NC}"
echo ""
echo "  1. ${YELLOW}Can you get a micro HDMI cable (no adapter)?${NC}"
echo "     YES → Get cable, this will fix it"
echo "     NO  → Continue to step 2"
echo ""
echo "  2. ${YELLOW}Do you have another micro HDMI adapter to try?${NC}"
echo "     YES → Try it"
echo "     NO  → Continue to step 3"
echo ""
echo "  3. ${YELLOW}Can you try the other HDMI port on the Pi?${NC}"
echo "     YES → Try HDMI1 if you used HDMI0 (or vice versa)"
echo "     NO  → Continue to step 4"
echo ""
echo "  4. ${YELLOW}Can you add config.txt settings?${NC}"
echo "     YES → Add hdmi_force_hotplug and related settings"
echo "     NO  → You're stuck - need proper cable/adapter"
echo ""

echo -e "${BLUE}================================================================${NC}"
echo -e "${BLUE}   What I Recommend${NC}"
echo -e "${BLUE}================================================================${NC}"
echo ""
echo -e "${GREEN}BEST FIX: Get a proper micro HDMI to HDMI cable${NC}"
echo ""
echo "  Current setup:"
echo "    [Pi micro HDMI] → [adapter] → [HDMI cable] → [Victron]"
echo "       ❌ Adapter likely blocking I2C"
echo ""
echo "  Better setup:"
echo "    [Pi micro HDMI] → [micro HDMI to HDMI cable] → [Victron]"
echo "       ✅ Direct connection, all pins work"
echo ""
echo "  Cost: ~£5-15 / \$8-20"
echo "  Fixes: Touchscreen, audio over HDMI, better reliability"
echo ""

echo -e "${YELLOW}QUICK TEST: Try the other HDMI port first${NC}"
echo "  This is free and takes 2 minutes:"
echo "    1. sudo poweroff"
echo "    2. Move cable to other micro HDMI port"
echo "    3. Power on"
echo "    4. ./check-touchscreen-hardware.sh"
echo ""

echo -e "${BLUE}================================================================${NC}"
echo -e "${BLUE}   Technical Details${NC}"
echo -e "${BLUE}================================================================${NC}"
echo ""
echo "  Why adapters fail:"
echo "    - HDMI has 19 pins total"
echo "    - Pins 15 (SCL) and 16 (SDA) carry I2C for DDC/touchscreen"
echo "    - Cheap adapters only connect video pins (1-13, 19)"
echo "    - Pins 15+16 not connected = no I2C = no touchscreen"
echo ""
echo "  What we're seeing:"
echo "    - Video works ✓ (display showing image)"
echo "    - I2C bus empty ✗ (not even EDID at 0x50)"
echo "    - Touchscreen missing ✗ (no device at 0x38)"
echo ""
echo "  This proves: Video passes through, I2C does not."
echo ""
