// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: lvgl-demo

#ifndef _LVGL_DEMO_UI_H
#define _LVGL_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_screen_main.h"
#include "screens/ui_screen_charging.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_emboo_logowhite_png);    // assets/EMBOO_LogoWhite.png
LV_IMG_DECLARE(ui_img_emboo_logosunsetorange_png);    // assets/EMBOO_LogoSunsetOrange.png

// FONTS
LV_FONT_DECLARE(ui_font_DNR_Large);
LV_FONT_DECLARE(ui_font_Heading);
LV_FONT_DECLARE(ui_font_Label_Small);
LV_FONT_DECLARE(ui_font_Speed);
LV_FONT_DECLARE(ui_font_Value_Small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
